### ISSUE TITLE
Project 'default' not found

### ISSUE THREAD

**Issue by sol-idsnake** [Urigo/graphql-cli#1123]
**Describe the bug**
I followed the migration guide found in your repo here: [Here](https://github.com/Urigo/graphql-cli/blob/master/docs/MIGRATION.md#get-schema-is-no-longer-available) and [Here](https://github.com/Urigo/graphql-cli/blob/master/docs/MIGRATION.md#special-notes-for-prisma-users).
After that, my .graphqlrc.yml looks like this:
```
projects:
  app:
    schema: src/schema.graphql
  prisma:
    schema: /prisma.yml
    extensions:
      codegen:
        src/generated/prisma.graphql:
          - schema-ast
```

My prisma.yml:
```
endpoint: https://eu1.prisma.sh/Xxx/oldprisma/dev
datamodel: datamodel.prisma
# Ensures Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - graphql codegen --project prisma # instead of graphql get-schema
    - prisma generate
```

My package.json script:
`"gen": "graphql codegen --project prisma"`

When I run npm run gen, I get `× Project 'default' not found`, and that's where it ends. I can't figure out how to fix it.

package.json:
```
"dependencies": {
		"@graphql-codegen/schema-ast": "^1.13.4",
		"@test-graphql-cli/codegen": "^4.0.1-beta.6",
		"graphql": "^14.5.8",
		"graphql-cli": "^4.0.1-beta.6",
		"graphql-yoga": "^1.18.3",
		"prisma": "^1.34.10",
		"prisma-binding": "^2.3.16"
	},
```

**To Reproduce**
Follow the above.

**Expected behavior**
Generate a prisma.graphql file.

**Versions (please complete the following information):**
 - OS: `Windows 10`
