### ISSUE TITLE
[v4] error when running graphql codegen

### ISSUE THREAD

**Issue by waterdrop01** [Urigo/graphql-cli#1219]
Hello!
I encounter an error when running `./node_modules/.bin/graphql codegen`.
Here is the error:
```
./node_modules/.bin/graphql codegen
  ✖ Parse configuration
    → Cannot convert undefined or null to object
    Generate outputs
  Cannot convert undefined or null to object

```
And here is my config `.graphqlrc.yml`:
```
schema:
  - "https/remote/graphql":
    headers:
      Access-Key: "SECRET_KEY"
extensions:
  codegen:
    ./schema.graphql:
      - schema-ast
```
and here is my `package.json`:
```
{
  "name": "test",
  "devDependencies": {
    "@graphql-cli/codegen": "^1.15.2",
    "@graphql-codegen/schema-ast": "^1.15.2",
    "graphql-cli": "^4.0.0"
  }
}
```
I used to run (and love) `graphql-cli get-schema`. Seems this operation became more complicated with the new version?

Thanks for your help!

**Comment by dotansimha** [comment]
You are right, I managed to reproduce it here: https://codesandbox.io/s/zealous-germain-znpbt?file=/package.json

We are working on a fix. Thanks @waterdrop01

**Comment by dotansimha** [comment]
Oh just noticed that the structure is missing the `generates` key. 

Your config file should look like that:

```yaml
schema:
  - "https/remote/graphql":
    headers:
      Access-Key: "SECRET_KEY"
extensions:
  codegen:
    generates:
      ./schema.graphql:
	    plugins:
          - schema-ast
```

@kamilkisiela is it intentional? Maybe docs are wrong? 

Anyway, in codegen I'll add a check for missing `generates` key now :) 

@waterdrop01

**Comment by waterdrop01** [comment]
Thanks @dotansimha! Indeed I was missing the `generates` key (I copied from this page: https://github.com/Urigo/graphql-cli/blob/master/docs/MIGRATION.md#get-schema-is-no-longer-available)

Now I'm getting an auth error from my graphql endpoint, it says:
```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./schema.graphql
      ✖ Load GraphQL schemas
        → Unable to download schema from remote: x-hasura-admin-secret/x-hasura-access-key required, but not found
        Load GraphQL documents
        Generate
```
And I'm using this exact `.graphqlrc.yml` file (corrected with auth header key name):

```yml
schema:
  - "https://fqdn/v1/graphql":
    headers:
      x-hasura-admin-secret: "KEY"
extensions:
  codegen:
    generates:
      ./schema.graphql:
        - schema-ast
```
Any idea? Seem like the header isn't correctly set when graphql-cli send the request.

**Comment by dotansimha** [comment]
@waterdrop01 use this please: 

```yaml
schema:
  - "https://fqdn/v1/graphql":
      headers:
        x-hasura-admin-secret: "KEY"
extensions:
  codegen:
    generates:
      ./schema.graphql:
        plugins:
          - schema-ast
```

Please note that `headers` is a child field of your schema path, so it needs 2 more spaces. I also added the `plugins` for the codegen setup because it's more clear (it's not required, but I think it's simpler).
