### ISSUE TITLE
`utils.memoize2of4` is not a function

### ISSUE THREAD

**Issue by Jomik** [Urigo/graphql-cli#1879]
**Describe the bug**
It complains about a missing function, `utils.memoize2of4`.

**To Reproduce**
1. run `graphql codegen`

**Expected behavior**
It executes without error and writes my schema to the given file.

**Screenshots**
![image](https://user-images.githubusercontent.com/699655/157263695-f41072ec-008e-4735-a01d-cf3730adc5f8.png)

**Versions (please complete the following information):**
- "@graphql-cli/codegen": "2.2.3",
- "@graphql-codegen/schema-ast": "2.4.1",
- "graphql-cli": "4.1.0",

**Additional context**
```yml
schema:
  - './schema.graphql'
documents: './src/**/*.{ts,tsx}'
extensions:
  languageService:
    useSchemaFileDefinitions: true
  codegen:
    generates:
      ./schema.graphql:
        schema:
          - ./data/relay-compiler-directives.graphql
          - https://a.url.com/graphql:
              headers:
                Authorization: $GRAPHQL_INTROSPECTION_TOKEN
        plugins:
          - schema-ast
 ```
```json
  "resolutions": {
    "graphql": "15.5.3",
    "graphql-config": "4.1.0"
  },
```
