### ISSUE TITLE
Output path cannot be determined for "prepare"

### ISSUE THREAD

**Issue by FredyC** [Urigo/graphql-cli#303]
In my Prisma project running `yarn graphql prepare -p database` I am getting following output.

> × Processing schema imports for project database...
> Output path cannot be determined. No existing configuration found and no output parameter specified.

Is there some change and the path is under a different key than `prepare-binding`? The path `src/generated` does exist and the `src/generated/prisma.graphql` is present as well.

_graphql-cli@2.16.0_

```yml
projects:
  app:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4000'
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: src/database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```
