### ISSUE TITLE
existsDelegate does not exist on type 'Prisma'

### ISSUE THREAD

**Issue by parweb** [Urigo/graphql-cli#316]
Hi

I cloned the project, a while ago it was working fine until 2 or 3 weeks
https://github.com/prismagraphql/graphql-server-example

versions:
- node: v10.3.0
- npm: 6.1.0

package.json
```
{
  "name": "backend",
  "version": "1.0.0",
  "scripts": {
    "dev": "npm-run-all --parallel start playground",
    "start": "nodemon -e ts,graphql -x ts-node -r dotenv/config src/index.ts",
    "playground": "graphql playground",
    "build": "rm -rf dist && graphql codegen && tsc",
    "prisma": "prisma"
  },
  "dependencies": {
    "apollo-engine": "1.1.1",
    "aws-sdk": "2.250.1",
    "bcryptjs": "2.4.3",
    "content-type": "1.0.4",
    "express": "4.16.3",
    "graphql-yoga": "1.14.6",
    "jsonwebtoken": "8.2.2",
    "mime-types": "2.1.18",
    "multiparty": "4.1.4",
    "ndjson": "1.5.0",
    "prisma-binding": "2.0.2",
    "raw-body": "2.3.3",
    "request": "2.87.0",
    "uuid": "3.2.1"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.1",
    "dotenv": "6.0.0",
    "graphql-cli": "2.16.1",
    "nodemon": "1.17.5",
    "npm-run-all": "4.1.3",
    "prisma": "1.8.3",
    "ts-node": "6.1.0",
    "typescript": "^2.9.1"
  },
  "prettier": {
    "semi": false,
    "trailingComma": "all",
    "singleQuote": true
  }
}
```

src/generated/prisma.ts(14087,62): error TS2339: Property 'existsDelegate' does not exist on type 'Prisma'.

**Comment by pixelbacon** [comment]
++

Same issue, same versions.

**Comment by codepunkt** [comment]
newer `prisma` and `prisma-binding` versions, same problem.

**Comment by pixelbacon** [comment]
I believe the issue is using `prisma-ts`, compared to now directly using `prisma-bindings` as seen in the [prisma/graphql-example-server](https://github.com/prismagraphql/graphql-server-example)

Got it working using the following `.graphqlconfig.yml`

```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:4000"
  db:
    schemaPath: src/generated/database.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: prisma/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts
```
