### ISSUE TITLE
Get schema replace prisma entrypoint

### ISSUE THREAD

**Issue by jon-ht** [Urigo/graphql-cli#328]
Hi,

I have following files
```
# .graphqlconfig.yml
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/database.graphql
    extensions:
      prisma: prisma/prisma.yml
      prepare-binding:
        output: src/generated/database.js
        generator: binding-js
```

```
# prisma.yml
endpoint: http://localhost:8866/my-api/dev
datamodel: datamodel.graphql

hooks:
  post-deploy:
    - graphql get-schema --project prisma
    - graphql prepare
```

```
# docker-compose.yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.9
    restart: always
    ports:
    - "8866:8866"
    environment:
      PRISMA_CONFIG: |
        port: 8866
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:

```

Has you can notice, i changed port `4466` by `8866`.

When I run `graphql get-schema --project prisma`, I get this output `‼ request to http://localhost:4466/my-api/dev failed, reason: connect ECONNREFUSED 127.0.0.1:4466`

I tried to add 
```
endpoints:
  default: http://localhost:8866
```
under `prisma.extensions`, but same result

Any idea or suggestion ?
