### ISSUE TITLE
.graphqlconfig.yml doesn't see env variables

### ISSUE THREAD

**Issue by SilencerWeb** [Urigo/graphql-cli#331]
.graphqlconfig.yml doesn't see env variables, but other .yml files(e.g. prisma.yml) does
I tried to set variables in scripts inside package.json(e.g. `"deploy:p": "NODE_ENV=production prisma deploy"`
tried to use `dotenv-cli`, it doesn't work anyway

.graphqlconfig.yml example:
```yml
projects:
  app:
    schemPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.${env:NODE_ENV}.yml
```

graphql-cli version - ^2.16.4

For more information, please read [this discussion](https://www.prisma.io/forum/t/set-up-environment-with-env/3844)

P.S. Here is screenshot of logs:
![image](https://user-images.githubusercontent.com/20713191/42235459-4410c930-7f11-11e8-81e5-c5f08d26b333.png)

**Comment by brunocascio** [comment]
any update here?

**Comment by SilencerWeb** [comment]
@brunocascio doesn't seem it will ever be

**Comment by marktani** [comment]
Could you please provide a reproducible example of what is happening?
What do you expect to happen instead?
What version of `graphql-cli` do you use, and what's your OS?

Thanks!

**Comment by SilencerWeb** [comment]
[Repo with example](https://github.com/SilencerWeb/graphqlconfig.yml-bug)

Try to run `yarn deploy:development` or `yarn deploy:production`.

Right now it throws error `graphqlconfig.yml-bug/prisma/prisma.${env:NODE_ENV}.yml could not be found.`
But it should find `graphqlconfig.yml-bug/prisma/prisma.deploy:development.yml` or `graphqlconfig.yml-bug/prisma/prisma.deploy:production.yml`, depends on script was ran.

Versions:
`graphql-cli` - 2.16.5
OS - macOS 10.13.6

@marktani

**Comment by SilencerWeb** [comment]
@marktani any news?

**Comment by tianhuil** [comment]
I'm currently using `envsubst` to get environment variables in but it's definitely not as good of a solution as `dotenv-cli`.

**Comment by nickreynke** [comment]
Any updates here?

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0`.
GraphQL Config has been rewritten with env variables support etc.
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We've just released a new version and an alpha release channel for GraphQL CLI - `4.0.0-alpha.XXX`!

We've also moved to use the new `alpha` version of [`graphql-config`](https://medium.com/the-guild/graphql-config-708dd0e5d15f) which has been rewritten with env variables support etc.

Checkout new instructions and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) and we will be happy to hear your feedback during the alpha period!

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9

**Comment by samuelcastro** [comment]
Was this fixed after all @Urigo, I'm trying to use ENV from the yml file but it's not working, this is what I have:

```yml
schema: 
  - http://localhost:3003/v1/graphql:
      headers:
        Authorization: ${ENV.AUTH_KEY}
extensions:
  codegen:
    generates:
      ./schema.graphql:
        - schema-ast
      ./src/common/types/generated-types.tsx:
        plugins:
          - typescript
          - typescript-operations
```
