### ISSUE TITLE
`graphql get-schema` doesn't work when prisma.yml has additional properties

### ISSUE THREAD

**Issue by nikolasburk** [Urigo/graphql-cli#341]
**Describe the bug**

This is what my `prisma.yml` looks like:

```yml
endpoint: https://eu1.prisma.sh/nikolas-burk/hackernews-node-pc/dev
datamodel: datamodel.graphql

generate:
  - generator: typescript
    output: ../src/generated/prisma.ts

hooks:
  post-deploy:
    - yarn graphql get-schema --project prisma
```

And this is my `.graphqlconfig`:

```yml
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
```

Running `get-schema` produces the following error:

```
~/D/hackernews-node-pc $ yarn graphql get-schema --project prisma
yarn run v1.3.2
$ graphql get-schema --project prisma
✖ Invalid prisma.yml file
prisma.yml should NOT have additional properties. additionalProperty: generate
```

![image](https://user-images.githubusercontent.com/4058327/44779735-8f1ce800-ab80-11e8-98a9-49635bae3385.png)

**Expected behavior**

GraphQL CLI should ignore additional properties in prisma.yml and just download the schema.
