### ISSUE TITLE
get-schema not generating file

### ISSUE THREAD

**Issue by bayerlse** [Urigo/graphql-cli#360]
**Describe the bug**
When running "graphql get-schema --project xxx" with correct .graphqlconfig.yaml defined, is not creating my schema.grapqhl file despite process finished correctly.

**Expected behavior**
The file should be created.

**.graphqlconfig.yaml**
```
projects:
  xxx:
    schemaPath: src/shared/graphql/schema.graphql
    extensions:
      endpoints:
        yyy:
          url: 'http://localhost:3001/graphql'
          subscription: 'ws://localhost:3001/subscriptions'
```

**Versions (please complete the following information):**
 - OS: Windows 10
 - `graphql-cli`: 2.17.0
