### ISSUE TITLE
The codegen plugin doesn't work with @graphql-codegen/add

### ISSUE THREAD

**Issue by tjpeden** [Urigo/graphql-cli#644]
**Describe the bug**
When using `@graphql-codegen/add` with `graphql-cli@canary` and `@test-graphql-cli/codegen@canary` the following error occurs.

```
✖ Cannot find module '@graphql-codegen/[object Object]'
```

The object it's referring to here is the plugin entry:
```yaml
schema: schema.graphql
extensions:
  codegen:
    src/index.ts:
      - add: '/* tslint: disable */'
      - typescript
```

**To Reproduce**
1. [Clone this Repo](https://github.com/tjpeden/graphql-cli-repro)
2. Run `graphql codegen` (or use `npm|yarn run generate`)

**Expected behavior**
Should generate a typescript file (`src/index.ts`) with `/* tslint: disable */` at the top.

**Versions (please complete the following information):**
 - OS: Linux Mint 19.2
 - `graphql-cli`: 2.2.1-alpha-dca1d95.425
 - Full dependencies list:
    ```
    {
      "dependencies": {
        "@graphql-codegen/add": "1.8.3",
        "@graphql-codegen/typescript": "1.8.3",
        "@test-graphql-cli/codegen": "^4.0.0-alpha.26",
        "graphql": "^14.5.8",
        "graphql-cli": "^2.2.1-alpha-dca1d95.425"
      }
    }
    ```
