### ISSUE TITLE
Parse configuration → Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by fnduister** [Urigo/graphql-cli#923]
Hi,
When trying to convert a simple graphql schema, i'm getting this error
  × Parse configuration
    → Cannot convert undefined or null to object

1. create .graphql.yml with this content
```
schema: ./src/**/*.graphql
extensions:
  codegen:
    ./generated-backend.ts:
      plugins:
        - typescript
```

2. npx graphql-cli@next init

2. choose backend only, no generation, typescript
3. yarn graphql codegen
4. See error: Parse configuration → Cannot convert undefined or null to object

**Expected behavior**
should generation typescipt types

**Screenshots**
![graphql](https://user-images.githubusercontent.com/3222355/74673441-2ca51680-517d-11ea-99a6-fc02e28a4551.PNG)
![graphql1](https://user-images.githubusercontent.com/3222355/74673569-7130b200-517d-11ea-9f63-9b1e9743ec87.PNG)

**Versions (please complete the following information):**
 - OS: windows10
 - `graphql-cli`: 4.0.1-beta.2

**Comment by wtrocki** [comment]
I think this is due to missing required documents section in config.
At least this is what it was for myself
It seems like validation issue in config.

**Comment by wtrocki** [comment]
Did this solved the issue. Feel free to reopen if needed.

**Comment by olso** [comment]
This worked for me

```yml
schema: http://localhost:8081/graphql
extensions:
  codegen:
    ./schema.graphql:
      - schema-ast
    generates:
      src/client/types.ts:
        - typescript
```

**Comment by arjun-kava** [comment]
@olso , Thank you. It also worked for me.

**Comment by olso** [comment]
@arjun-kava Also if you have custom scalars, you can type them 🙂

```
schema: http://localhost:8081/graphql

config:
  scalars:
    DateTime: string
    Money: string

generates:
  src/types/Generated.ts:
    - typescript
```
